export const data = [
    {
        key: '1',
        salaryGrade: 'Ngạch lương quản lý - Điều hành',
        applyFor: 'Thành viên ban giám đốc; Trợ lý giám đốc; Giám đốc sản xuất; ',
        salaryScale: 'QLDH',
        coefficient: [3, 0.4],
        coefficientAvg: 3,
        basicSalary: 'LCB',
        kpiPercent: '%',
        kpiSalary: 'LKPI',
        allowancePercent1: '%',
        allowance: 'PC1',
        allowancePercent2: '%',
        allowance2: 'PC2',
        positionSalary: 'LVT1',
        positionSalaryHaveAllowance: 'LVT2',
        note: '',
        children: [
            {
                key: '1.1',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.2',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.3',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.4',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.5',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.6',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.7',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            }
        ]
    },
    {
        key: '2',
        salaryGrade: 'Ngạch lương nhan vien',
        applyFor: 'Nhan vien',
        salaryScale: 'QLNS',
        coefficient: [2, 0.2],
        coefficientAvg: 2,
        basicSalary: 'LCB',
        kpiPercent: '%',
        kpiSalary: 'LKPI',
        allowancePercent1: '%',
        allowance: 'PC1',
        allowancePercent2: '%',
        allowance2: 'PC2',
        positionSalary: 'LVT1',
        positionSalaryHaveAllowance: 'LVT2',
        note: '',
        children: [
            {
                key: '2.1',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.2',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.3',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.4',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.5',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.6',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.7',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                coefficientAvg: 1,
                basicSalary: 0,
                kpiPercent: 30,
                kpiSalary: 0,
                allowancePercent1: 40,
                allowance: 0,
                allowancePercent2: 50,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            }
        ]
    }
]


export const pcCols = [
    {
        title: 'Phụ cấp 01'
    }
]
