export const data = [
    {
        key: '1',
        ngachLuong: 'Ngạch lương quản lý - Điều hành',
        apDung: [1, 3],
        index: '1',
        bacLuong: 'QLDH',
        heSo: [3, 0.4],
        loaiHeSo: 1,
        heSoTB: 3,
        luongViTri: 'LVT',
        lcbPercent: '%LCB',
        lcbDefault: 70,
        lcb: 'LCB',
        kpiPercent: '%KPI',
        kpiDefault: 30,
        lkpi: 'L(KPI)',
        phuCapDefault: 40,
        phuCapUnit1: '%',
        phuCapValue1: 'PC',
        tong: 'LVT+PC',
        ghiChu: '',
        children: [
            {
                key: '1.1',
                ngachLuong: 'sol1',
                index: '1.1',
                bacLuong: 'QLDH - B1',
                heSo: 1.8,
                luongViTri: 0,
                lcbPercent: null,
                lcb: 5670000,
                kpiPercent: null,
                lkpi: 2430000,
                phuCapUnit1: '2',
                phuCapValue1: 113400,
                tong: 8213400,
                ghiChu: ''
            },
            {
                key: '1.2',
                ngachLuong: 'sol2',
                index: '1.2',
                bacLuong: 'QLDH - B2',
                heSo: 2.2,
                luongViTri: 9900000,
                lcbPercent: null,
                lcb: 6930000,
                kpiPercent: null,
                lkpi: 2970000,
                phuCapUnit1: '2',
                phuCapValue1: 138600,
                tong: 10038600,
                ghiChu: ''
            },
            {
                key: '1.3',
                ngachLuong: 'sol3',
                index: '1.3',
                bacLuong: 'QLDH - B3',
                heSo: 2.6,
                luongViTri: 11700000,
                lcbPercent: null,
                lcb: 8189999.999999999,
                kpiPercent: null,
                lkpi: 3510000,
                phuCapUnit1: '2',
                phuCapValue1: 163799.99999999997,
                tong: 11863800,
                ghiChu: ''
            },
            {
                key: '1.4',
                ngachLuong: 'sol4',
                index: '1.4',
                bacLuong: 'QLDH - B4',
                heSo: 3.0,
                luongViTri: 13500000,
                lcbPercent: null,
                lcb: 9450000,
                kpiPercent: null,
                lkpi: 4050000,
                phuCapUnit1: '2',
                phuCapValue1: 189000,
                tong: 13689000,
                ghiChu: ''
            },
            {
                key: '1.5',
                ngachLuong: 'sol5',
                index: '1.5',
                bacLuong: 'QLDH - B5',
                heSo: 3.4,
                luongViTri: 15300000,
                lcbPercent: null,
                lcb: 10710000,
                kpiPercent: null,
                lkpi: 4590000,
                phuCapUnit1: '2',
                phuCapValue1: 214200,
                tong: 15514200,
                ghiChu: ''
            },
            {
                key: '1.6',
                ngachLuong: 'sol5',
                index: '1.6',
                bacLuong: 'QLDH - B6',
                heSo: 3.8,
                luongViTri: 17100000,
                lcbPercent: null,
                lcb: 11970000,
                kpiPercent: null,
                lkpi: 5130000,
                phuCapUnit1: '2',
                phuCapValue1: 239400,
                tong: 17339400,
                ghiChu: ''
            },
            {
                key: '1.7',
                ngachLuong: 'sol5',
                index: '1.7',
                bacLuong: 'QLDH - B7',
                heSo: 4.2,
                luongViTri: 18900000,
                lcbPercent: null,
                lcb: 13230000,
                kpiPercent: null,
                lkpi: 5670000,
                phuCapUnit1: '2',
                phuCapValue1: 264600,
                tong: 19164600,
                ghiChu: ''
            }
        ]
    },
    {
        key: '2',
        ngachLuong: 'Ngạch lương quản lý - Điều hành',
        apDung: [1, 3],
        index: '1',
        bacLuong: 'QLDH',
        heSo: [3, 0.4],
        loaiHeSo: 1,
        heSoTB: 3,
        luongViTri: 'LVT',
        lcbPercent: '%LCB',
        lcbDefault: 70,
        lcb: 'LCB',
        kpiPercent: '%KPI',
        kpiDefault: 30,
        lkpi: 'L(KPI)',
        phuCapDefault: 40,
        phuCapUnit1: '%',
        phuCapValue1: 'PC',
        tong: 'LVT+PC',
        ghiChu: '',
        children: [
            {
                key: '2.1',
                ngachLuong: 'sol1',
                index: '1.1',
                bacLuong: 'QLDH - B1',
                heSo: 1.8,
                luongViTri: 0,
                lcbPercent: null,
                lcb: 5670000,
                kpiPercent: null,
                lkpi: 2430000,
                phuCapUnit1: '2',
                phuCapValue1: 113400,
                tong: 8213400,
                ghiChu: ''
            },
            {
                key: '2.2',
                ngachLuong: 'sol2',
                index: '2.2',
                bacLuong: 'QLDH - B2',
                heSo: 2.2,
                luongViTri: 9900000,
                lcbPercent: null,
                lcb: 6930000,
                kpiPercent: null,
                lkpi: 2970000,
                phuCapUnit1: '2',
                phuCapValue1: 138600,
                tong: 10038600,
                ghiChu: ''
            },
            {
                key: '2.3',
                ngachLuong: 'sol3',
                index: '2.3',
                bacLuong: 'QLDH - B3',
                heSo: 2.6,
                luongViTri: 11700000,
                lcbPercent: null,
                lcb: 8189999.999999999,
                kpiPercent: null,
                lkpi: 3510000,
                phuCapUnit1: '2',
                phuCapValue1: 163799.99999999997,
                tong: 11863800,
                ghiChu: ''
            },
            {
                key: '2.4',
                ngachLuong: 'sol4',
                index: '2.4',
                bacLuong: 'QLDH - B4',
                heSo: 3.0,
                luongViTri: 13500000,
                lcbPercent: null,
                lcb: 9450000,
                kpiPercent: null,
                lkpi: 4050000,
                phuCapUnit1: '2',
                phuCapValue1: 189000,
                tong: 13689000,
                ghiChu: ''
            },
            {
                key: '2.5',
                ngachLuong: 'sol5',
                index: '2.5',
                bacLuong: 'QLDH - B5',
                heSo: 3.4,
                luongViTri: 15300000,
                lcbPercent: null,
                lcb: 10710000,
                kpiPercent: null,
                lkpi: 4590000,
                phuCapUnit1: '2',
                phuCapValue1: 214200,
                tong: 15514200,
                ghiChu: ''
            },
            {
                key: '2.6',
                ngachLuong: 'sol5',
                index: '2.6',
                bacLuong: 'QLDH - B6',
                heSo: 3.8,
                luongViTri: 17100000,
                lcbPercent: null,
                lcb: 11970000,
                kpiPercent: null,
                lkpi: 5130000,
                phuCapUnit1: '2',
                phuCapValue1: 239400,
                tong: 17339400,
                ghiChu: ''
            },
            {
                key: '2.7',
                ngachLuong: 'sol5',
                index: '2.7',
                bacLuong: 'QLDH - B7',
                heSo: 4.2,
                luongViTri: 18900000,
                lcbPercent: null,
                lcb: 13230000,
                kpiPercent: null,
                lkpi: 5670000,
                phuCapUnit1: '2',
                phuCapValue1: 264600,
                tong: 19164600,
                ghiChu: ''
            }
        ]
    },
]

export const pcCols = [
    {
        key: 1,
        title: 'Phụ cấp 01'
    }
]
