export const data = [
    {
        key: '1',
        salaryGrade: 'Ngạch lương quản lý - Điều hành',
        applyFor: [1, 3],
        salaryScale: 'QLDH',
        coefficient: [3, 0.4],
        coefficientFlg: false,
        coefficientAvg: 3,
        basicSalary: 'LCB',
        kpiPercent: '%',
        kpiDefault: 30,
        kpiSalary: 'LKPI',
        allowancePercent1: '%',
        allowanceDefault: 40,
        allowance: 'PC1',
        allowancePercent2: '%',
        allowanceDefault2: 50,
        allowance2: 'PC2',
        positionSalary: 'LVT1',
        positionSalaryHaveAllowance: 'LVT2',
        note: '',
        hidden: false,
        children: [
            {
                key: '1.1',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.2',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.3',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.4',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.5',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.6',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '1.7',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            }
        ]
    },
    {
        key: '2',
        salaryGrade: 'Ngạch lương nhan vien',
        applyFor: [4],
        salaryScale: 'QLNS',
        coefficient: [2, 0.2],
        coefficientFlg: false,
        coefficientAvg: 2,
        basicSalary: 'LCB',
        kpiPercent: '%',
        kpiDefault: 30,
        kpiSalary: 'LKPI',
        allowancePercent1: '%',
        allowanceDefault: 40,
        allowance: 'PC1',
        allowancePercent2: '%',
        allowanceDefault2: 50,
        allowance2: 'PC2',
        positionSalary: 'LVT1',
        positionSalaryHaveAllowance: 'LVT2',
        note: '',
        hidden: false,
        children: [
            {
                key: '2.1',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.2',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.3',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.4',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.5',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.6',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            },
            {
                key: '2.7',
                salaryGrade: '',
                salaryScale: '',
                coefficient: 1,
                basicSalary: 0,
                kpiPercent: null,
                kpiSalary: 0,
                allowancePercent1: null,
                allowance: 0,
                allowancePercent2: null,
                allowance2: 0,
                positionSalary: 0,
                positionSalaryHaveAllowance: 0,
                note: ''
            }
        ]
    }
]

export const pcCols = [
    {
        title: 'Phụ cấp 01'
    }
]

